### ISSUE TITLE
No MathJax Icon in tinymce

### ISSUE THREAD

**Issue by fradrick** [SoftwareMansion/tinymceMathjax#7]
Good day.

I followed the instructions on the readme file, and ran npm run build. I copied the the mathjax folder produced to tinmyce/plugins folder in included under tinymce plugins configuration; on setting up the editor in html. Added mathjax to toolbar but its not visible.

Help!!

**Comment by sebryu** [comment]
Hello Fradrick!

Thank you for your report. First of all, please write down which version of tinymce do you use, it will help me debug the problem.
Second thing is that I didn't edited this plugin readme, so it might be incomplete, but I will try to look at your issue and help you.

**Comment by fradrick** [comment]
Thank you for your quick response. I am using tinymce 4.

I realised where I was making a mistake, instead of inserting ' asciimath asciimathcharmap toggleMath' on the toolbar i had been inserting 'mathjax', but the issue has been resolved.

Thank you!
